#simple python print example
print "Hello harin"
print "welcome to python"
print "Use of the print function"
print "I love programming"
print "simple print function"
print "Hello friends"
print "hello github"
print "Hello again"
print "Let's learn english"
print "I love python..."